version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ctf-nginx
    restart: always
    ports:
      - "80:80"  # SSL 없이 HTTP로만 실행
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf:ro  # 로컬 테스트용 설정 파일
    depends_on:
      - app
    networks:
      - ctf-network
